# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['md-converter-gui\\main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('pictures', 'pictures'),
        ('image', 'image'),
        ('imarkdown', 'imarkdown'),
    ],
    hiddenimports=[
        'qcloud_cos',
        'qiniu',
        'boto3',
        'botocore',
        'urllib3',
        'PIL',
        'PIL._imagingtk',
        'PIL._tkinter_finder',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'qtawesome',
        'PyQt6.QtQml',
        'PyQt6.QtWebEngineCore',
        'PyQt6.QtWebEngineWidgets',
        'PyQt6.QtNetwork',
        'PyQt6.QtTest',
        'PyQt6.QtSql',
        'PyQt6.QtMultimedia',
        'PyQt6.QtChart',
        'PyQt6.QtBluetooth',
        'PyQt6.QtNfc',
        'PyQt6.QtPositioning',
        'PyQt6.QtSensors',
        'PyQt6.QtSerialPort',
        'PyQt6.QtWebChannel',
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'jupyter',
        'notebook',
        'ipython',
        'tkinter',
        'tk',
        'tcl',
        'ssl',
        'unittest',
        'doctest',
        'pdb',
        'pydoc',
        'difflib',
        'sqlite3',
        'xmlrpc',

        'urllib.parse',
        'urllib.request',
        'urllib.robotparser',
        'html',

        'setuptools',
        'pip',
    ],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MdImgConverter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='pictures/app_icon.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='MdImgConverter',
)
